#!/bin/bash
#Simple backup script v1.3 (by BOBdotEXE)
echo Creating Save File backup now!
workingDir="/home/pi/RetroPie/roms/"
backupDir="/home/pi/RetroPie/roms/backups"
archiveFolderName="RetroPiSaves"
#backup dir may be relitive.
cd  $workingDir
#USA format
timestamp="$(date +'%m-%d-%Y_%H.%M.%S')"
#Proper format
#timestamp="$(date +'%d-%m-%Y_%H.%M.%S')"
[ -d $backupDir ] || mkdir $backupDir 
[ -d $backupDir/$archiveFolderName ] || mkdir $backupDir/$archiveFolderName
find . | egrep "\.(sav|srm)$" | zip -@ $backupDir/"$archiveFolderName"/Backup-"$timestamp".zip
md5=($(md5sum "$backupDir"/"$archiveFolderName"/Backup-"$timestamp".zip))
echo $md5 >> "$backupDir"/"$archiveFolderName"/Backup-"$timestamp".md5
echo " "
echo "Backup Completed!"
echo "Saved to $(date +'%m-%d-%Y_%H.%M.%S').zip"
echo "And md5 created for verification!"
echo "Uploading to Google Drive..."
cd $backupDir
./drive push
